### ISSUE TITLE
There already is a project called JINQ

### ISSUE THREAD

**Issue by my2iu** [TheRealMarnes/HighLevelCollections#1]
Hey, it's not a problem, but I just wanted to let you know that I already have a project called Jinq which implements LINQ for Java. If you want to use the same name, that's fine. I just wanted to let you know because people might have a hard time finding your project if it uses the same name.

**Comment by TheRealMarnes** [comment]
Hmm, thankd for letting me know. I'll try to come up with something else to avoid confusion.

**Comment by TheRealMarnes** [comment]
Renamed to HighLevelCollections, which is more appropriate anyway since my code doesn't exactly relate to queries
